language: go
go:
  - tip
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - make depend

before_script:
  make build

script:
  - export NAME=`basename $TRAVIS_BUILD_DIR`
  - echo NAME=$NAME
  # - make travis-test

deploy:
  provider: releases
  github-token: $GH_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    branch: master
    tags: true